main: info.gomeow.metahandler.MetaHandler
name: MetaHandler
version: 1.0.0

commands:
  meta:
    description: All MetaHandler commands
    aliases: [mh, metahandler]
permissions:
  metahandler.*:
    children:
      metahandler.item: true
      metahandler.skull: true
      metahandler.map: true
      metahandler.leather: true
      metahandler.book: true